apiVersion: apps/v1
kind: Deployment
metadata:
  name: team4-spring-dev
  labels:
    app: team4-spring
    env: dev
spec:
  selector:
    matchLabels:
      app: team4-spring
      env: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: team4-spring
        env: dev
    spec:
      containers:
      - image: igagankalra/team4-spring-devimage
        name: spring-dev
        ports:
        - containerPort: 8080

