apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dev
  labels:
    app: spring
    env: dev
spec:
  selector:
    matchLabels:
      app: spring
      env: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring
        env: dev
    spec:
      containers:
      - image: eashish/spring
        name: spring-dev
        ports:
        - containerPort: 8080

