FROM tomcat:7-jre7-alpine
RUN rm -rf /usr/local/tomcat/webapps/*
COPY target/Spring3HibernateApp.war /usr/local/tomcat/webapps/ROOT.war
WORKDIR /usr/local/tomcat/webapps/
COPY  terraform_code/ terraform_code/
EXPOSE 8080
CMD ["/bin/sh","-c","echo $(cat terraform_code/terraform.dev/instance_ip_dev) mysql | tr -d '\"' >> /etc/hosts && catalina.sh run"]
