FROM tomcat:7-jre7-alpine
MAINTAINER "Ashish Saxena"
RUN rm -rf /usr/local/tomcat/webapps/*
COPY target/Spring3HibernateApp.war /usr/local/tomcat/webapps/ROOT.war
WORKDIR /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["/bin/sh","-c","echo '54.226.49.137 mysql' >> /etc/hosts && catalina.sh run"]
