FROM tomcat:7-jre7-alpine
RUN rm -rf /usr/local/tomcat/webapps/*
COPY target/Spring3HibernateApp.war /usr/local/tomcat/webapps/ROOT.war
WORKDIR /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["/bin/sh","-c","echo $(cat terraform_code/terraform.prod/instance_ip_prod) mysql >> /etc/hosts && catalina.sh run"]
CMD ["cat /etc/hosts"]