apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-prod
  labels:
    app: spring-prod
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-prod
      env: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: spring-prod
        env: prod
    spec:
      containers:
      - image: igagankalra/team4-spring 
        name: spring-prod
        ports:
        - containerPort: 8080

